package plt.fds.filetranslator.data_models;

public enum EnumOrbitalEventTypes {
    ASCENDING_NODE_CROSSING,
    DESCENDING_NODE_CROSSING,
    SUN_VISIBILITY,
    MOON_VISIBILITY,
    EARTH_UMBRA,
    EARTH_PENUMBRA,
    MOON_UMBRA,
    MOON_PENUMBRA,
    SUN_SAT_EARTH_COLINEARITY,
    SUN_SAT_STN_COLINEARITY,
    APOGEE_CROSSING,
    PERIGEE_CROSSING,
}
